### ISSUE TITLE
Project: Use Twinkles Postage Stamps to run Scarlet

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTScienceCollaborations/StackClub#108]
I have two goals in this project:
1) Show how to load up truth information in the Twinkles data folder and use it to find strongly lensed systems in the Twinkles data.
2) Following the already existing blueprint for running scarlet in `scarlet_tutorial.ipynb` use it on postage stamps from Twinkles.

**Comment by drphilmarshall** [comment]
Sounds good to me! The scarlet tutorials have exercises in them, for the
user to fiddle with the configurations, constraints etc. You could do
likewise, but don't feel you have to! I'm guessing that you would like to
know how best to set up _Scarlet_ to deblend lensed quasars in coadd
images, so you could either tune the notebook yourself and present it like
this, or set an exercise but provide a hidden answer in a small external
python file and a #%load cell. This is going to be fun, @jbkalmbach :-)

**Comment by drphilmarshall** [comment]
Update on this project: @fred3m is updating the 2 Scarlet tutorial notebooks, and then recommends that for the Twinkles objects we consider running the `MultibandCoaddMeasurementTask` (or somesuch) to see what it produces, using Scarlet under the hood. We'll still need a list of lenses and non-lenses to explore, but once we have them, its this task that will carry out the deblending of the DRP Objects. The scarlet tutorial to jump off from is [`Deblending/lsst_stack_deblender.ipynb`](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Deblending/lsst_stack_deblender.ipynb).

**Comment by jbkalmbach** [comment]
@drphilmarshall Sounds good. I will look at the tutorial notebooks and get back up to speed. I'm back to learn about deblending now that I've passed my defense (yay!).

**Comment by fred3m** [comment]
Congratulations on passing your defense! At the end of this week the LSST stack will be updated with the new scarlet API, as well as the stack club notebooks. So it might be best to wait a week, and take a look at the updated version next Monday.

**Comment by jbkalmbach** [comment]
@fred3m are there updated notebooks available? It seems that the current scarlet notebooks are failing.

**Comment by fred3m** [comment]
Unfortunately not yet. I'll try to get them done at some point this week at the DESC meeting.

**Comment by kadrlica** [comment]
The scarlet and stack deblending notebooks should all be up to date, but I'm not sure if this project is still relevant, especially given that all notebooks are DC2-focused now. What do you think @jbkalmbach, should we close it?

**Comment by jbkalmbach** [comment]
Yeah, I think this can be closed since we've moved on to other data. Closing it now. Hopefully we can get run3.1 data in here at some point and try this.
