### ISSUE TITLE
Project: Overdensities in source density maps

### ISSUE THREAD

**Issue by jeffcarlin** [LSSTScienceCollaborations/StackClub#136]
I would like to create a tutorial showing some ways to search for and characterize overdensities in sky maps of the source density in some region of sky. I'm thinking that this will include aspects such as (a) creating density maps of sources selected based on CMD or color-color criteria, (b) exploring the distribution of objects classified as "star" vs. "galaxy" by the 'default' Stack classifier, and possibly tweaking the star/galaxy separation to see the effects, and (c) extracting sources in overdensities and plotting their properties (in, e.g., CMDs, color-color diagrams, density profiles, etc.).

I will use HSC data, but need to select a particularly illustrative field - preferably one with some known "overdensity" such as a Milky Way dwarf galaxy or a rich galaxy cluster.

**Comment by drphilmarshall** [comment]
This sounds good to me, Jeff! I think this belongs in the "Object
Measurement" part of the syllabus, in a folder called "Measurement". I'll
push a suitable folder with a README.rst in it for you. @kadrlica @bechtol
I think you'll be interested in this project! :-)

**Comment by kadrlica** [comment]
I think that this has been closed by #250
