### ISSUE TITLE
Project: Road-test all the Stack Club tutorials

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#140]
In a branch called `project/road-test/saharallam`, @saharallam is going to work through all the notebooks listed on the [Syllabus](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Syllabus.md), to learn the ropes and also fix any little bugs that have crept in. I guess you will probably have bigger suggestions too, Sahar - you could either suggest them by editing the notebooks and submitting a PR, or by issuing them here. Others: if you want to join in this exercise, you are more than welcome! Just make a local branch called `project/road-test/<username>` and off you go - you can then push to a remote branch of  the same name and contribute by PR in the usual way.

**Comment by Madejski** [comment]
Terrific!  But we might find it useful to document all bugs (more severe than say typos) here - what do you think @drphilmarshall ?

**Comment by drphilmarshall** [comment]
Sure: if you find a bug in a notebook and are not sure whether you should just fix it, or make a new issue for it, or what, please do post it in this thread and the rest of can advise.

**Comment by kadrlica** [comment]
I think this issue has been long closed.
