### ISSUE TITLE
Stack Club on Fri. Nov. 16th

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/StackClub#158]
Stack-club members,

We gather that many of you are attending the bootcamp at SLAC this week (week of Nov. 13th).  We thought that if it finishes by Thursday, and you can join in for the Club session on Friday Nov. 16, we would hold it.  Do let us know -- via commenting on slack, or as a comment below -- if you can or can't make it, and whether you would be able to show any of your recent work (or share any concerns).  If we hold it - the format would follow that from previous Fridays.  

If we end up holding it - we will use the usual zoom http://stanford.zoom.us/j/946390572

One more thing:  Fri. Nov. 23rd is the day after Thanksgiving, and many of the US participants are likely to have it as a vacation day.  We will skip the Club meeting on Fri. Nov. 23rd.  

--Alex, Greg and Phil

**Comment by SimonKrughoff** [comment]
We are planning to wrap up formal progress in the boot camp this afternoon. I think we can present a couple notebooks tomorrow.

**Comment by Madejski** [comment]
OK, so the Stack Club session is "on" for tomorrow, Nov. 16th;  I will do the MCing.  --Greg

**Comment by Madejski** [comment]
We will start in a few minutes.  --Greg

**Comment by drphilmarshall** [comment]
Friday's video is now up, on the Stack Club [Meetings page](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Meetings.md) - attn @TallJimbo ! I also put up the videos from our October sessions, in case anyone wants to revisit the discussion from those.
