### ISSUE TITLE
Stack Club meeting on Friday Nov. 30

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/StackClub#161]
Stack Club members, 

We will have our weekly Stack Club session this coming Friday, Nov. 30th, usual time, 9AM PST:  we will use the usual zoom http://stanford.zoom.us/j/946390572 .  The "featured presentation" will be by Simon Krughoff - it will cover the new notebooks from the Camera/Commissioning bootcamp which took place the week before Thanksgiving.  

--Alex, Greg and Phil

**Comment by Madejski** [comment]
We will start in a few minutes.  See you at zoom!  --Greg

**Comment by drphilmarshall** [comment]
This was a good session - great to hear more about the data for, and notebooks from, the Camera/Commissioning Bootcamp! Video is now up, on the [Meetings page](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Meetings.md).

**Comment by DouglasLeeTucker** [comment]
Thanks for adding it!  I missed that meeting, and am glad the videos are now available!

Best regards,
Douglas


--
=======================================================================
Douglas L. Tucker
Fermilab                        Tel:    +1-630-840-2267
MS 127                          FAX:    +1-630-840-8274
PO Box 500                      E-mail: dtucker@fnal.gov
Batavia, IL 60510 USA           http://home.fnal.gov/~dtucker/
=======================================================================
