### ISSUE TITLE
Stack Club Session, Friday December 7, 0900 PST

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#163]
Hi @LSSTScienceCollaborations/stack-club

Hope you're having a good week! This Friday we'll be hacking on our projects as usual, but we can also do:

1) a bit of iteration on our holiday party plan (December 21, in two weeks time, will be the last Stack Club meeting of 2018, so we're looking to design a suitably celebratory session!)

2) some discussion of how we'd like to see the Stack Club develop in "Phase 3", winter/spring 2019. 

We'll do 20 mins discussion of the above at the start, then a stand-up, then hack, then get back together to look at what we have made before we finish at 1100 PST. 

See you Friday, on http://stanford.zoom.us/j/946390572 !

Phil, Greg & Alex

PS. @rmorgan10 I wasn't sure if you wanted to show your dataset inventory project progress this week or later on - let me know!

**Comment by Madejski** [comment]
We will start in a few min.  --Greg, Phil, Alex
