### ISSUE TITLE
Project: Getting the deblending tutorials to successfully run

### ISSUE THREAD

**Issue by belaa** [LSSTScienceCollaborations/StackClub#166]
Right now the deblending tutorials for the scarlet and stack deblenders are failing to build. We need to fix this and make sure that other aspects of the tutorial are consistent with the latest version of the stack.

**Comment by drphilmarshall** [comment]
Thanks both! I've labelled this a project and assigned it to you, @belaa , with the understanding that once the de-blending notebooks are running again, you'll change the title to reflect the measurement-in-the-presence-of-deblending tutorial you want to write. Hope that sounds good!

**Comment by kadrlica** [comment]
Blast from the past, but @ismael2395 has started to tackle this (specifically, updates to the scarlet notebook) as part of the Stack Club Course.
