### ISSUE TITLE
Upgrade the Taster

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/StackClub#174]
This is a place for collecting some suggested updates to the Stack Club `Taster`.

**Comment by drphilmarshall** [comment]
Here's a suggestion for a `Taster` upgrade: have it report on which version of the Stack was used to generate the data, and (ideally) which tasks were run, and what the configurations were. I think the Stack version could be looked up by default, and the pipeline reconstruction done optionally. Data provenance of this kind has come up in discussion for me in a few places now, and it could be useful to have a `Taster` with this ability when the move to v17 happens (soon!)

**Comment by kadrlica** [comment]
@drphilmarshall I don't think there are any plans to update the `Taster` since the exploring a repo notebook has been moved to the Graveyard. Can this issue be closed?

**Comment by drphilmarshall** [comment]
Yes, I think so - this seems thoroughly stale, so let's close it out.

>
