### ISSUE TITLE
new LSP url(?)

### ISSUE THREAD

**Issue by ih64** [LSSTScienceCollaborations/StackClub#185]
From the dm-lsp channel on Slack: The domain name lsst-lspdev.ncsa.illinois.edu is deprecated and replaced by lsst-lsp-stable.ncsa.illinois.edu

The deprecated url will not let you access the LSP (at least for me). If this is the case, we may have to edit the templates and other references to the previous url

**Comment by drphilmarshall** [comment]
Thanks @ih64 - labeling this as a bug, to make sure we really do fix our templates and docs.
