### ISSUE TITLE
Stack Club meeting on Fri. 20th Sep 9AM Pacific

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/StackClub#223]
This coming Friday Sep. 20 is the "on" Friday for the Club - so, we'll meet at the usual time (9AM Pacific) and place  ( http://stanford.zoom.us/j/946390572 ).  We don't have any notebooks lined up for showcasing, but if you like to cover anything you are working on - please let us know!  Greg M. is travelling, but Keith B. and Alex D.-W. will be running it.  

Talk to you then, --Greg, Phil, Keith, and Alex

**Comment by DouglasLeeTucker** [comment]
Dear Greg et al.,

I am afraid I have a conflict tomorrow, but I did finally managed today to get around to reviewing and approving Imran’s pull request from late August (#221).

Let me know if I managed to botch my GitHub review/approval!

Thanks!

Best regards,
Douglas


--
=======================================================================
Douglas L. Tucker
Fermilab                        Tel:    +1-630-840-2267
MS 127                          FAX:    +1-630-840-8274
PO Box 500                      E-mail: dtucker@fnal.gov
Batavia, IL 60510 USA           http://home.fnal.gov/~dtucker/
=======================================================================
