### ISSUE TITLE
Stack Club Spring Course

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/StackClub#226]
We have been talking about starting a new phase of stack club where we teach a "course" targeting new users. This would probably mean something like six weeks where we hold one 2-hour session per week, followed by two weeks where participants work on "final projects" (i.e., their own notebooks).

The six-week course would be taught by current stack club members and would focus around the notebooks that we have already created.

The target start date would be somewhere around April 2020.

@Madejski @drphilmarshall what do you think? Would you be able to help me organize and advertise?

**Comment by RobertLuptonTheGood** [comment]
I'm not sure whether or not this is relevant.

We're running an intro to LSST stack things in Princeton in early December.  I think it'll be on blue jeans;  I think anyone will be welcome to attend remotely (but possibly muted)

					R

> We have been talking about starting a new phase of stack club where we teach a "course" targeting new users. This would probably mean something like six weeks where we hold one 2-hour session per week, followed by two weeks where participants work on "final projects" (i.e., their own notebooks).
> 
> The six-week course would be taught by current stack club members and would focus around the notebooks that we have already created.
> 
> The target start date would be somewhere around April 2020.
