### ISSUE TITLE
Can I download a load copy of the datafiles used in the aft_table_guided_tour tutorial

### ISSUE THREAD

**Issue by fklich** [LSSTScienceCollaborations/StackClub#256]
@drphilmarshall
  I'm enjoying the aft_table_guided_tour tutorial in my stand-alone environment on my MAC.  So far, so good.
  It calls for input data at:
file_path = '/datasets/hsc/repo/rerun/RC/v20_0_0_rc1/DM-25349-sfm/01327/HSC-Z/output/SRC-0038938-032.fits'
datadir    = "/datasets/hsc/repo/rerun/RC/v20_0_0_rc1/DM-25349/" 
  Please, is there a source where I can download this for my local testing?
Fred klich
Dallas, Tx
fappa@msn.com

**Comment by kadrlica** [comment]
Hi @fklich, these notebooks were only intended to be run from the Rubin Science Platform at NCSA. There is no support provided for running them elsewhere. In particular, some of the data sets that they use are multi-terabytes in size, and cannot be easily distributed.
