### ISSUE TITLE
Basics: A Guided Tour of an afwtable

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#51]
This came up in session 4 as a potentially useful resource: a simple tutorial notebook that exercises the methods of the afwtable class, so as to provide an interactive reference work. I expressed interest in making this but TBH anyone could take this on, there are plenty of good Table objects in the shared LSP datasets. Comments welcome - I'll leave this project unassigned so that others can volunteer to take it on.

**Comment by ih64** [comment]
Hi Phil,

I'd like to volunteer for this issue, if it has not been claimed already. I'm on the lsst commissioning team and have access to the science platform

best
Imran Hasan

**Comment by drphilmarshall** [comment]
@ih64 Good to see you at the PCW, and at the Club session this week. I just added you to the Stack Club team so you have write access to the repo. Looking fwd to seeing how your tutorial comes out - hopefully a nice addition to our "Level: Introductory" set :-)

**Comment by ih64** [comment]
discovered how to use the `find()` method in afw schemas, along with a few other convenience methods to deal with schemas that are really huge. These ought to go into the notebook, so I will add them in using my development branch
