### ISSUE TITLE
Project: Low surface brightness galaxy detection

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/StackClub#54]
I would like to break out the source detection (and measurement) section of `processCCD` to tweak and apply it to the search for low surface brightness galaxies. I've started with the twinkles data set, but HSC might be better with known LSB catalog from [Greco et al. 2017](https://arxiv.org/abs/1709.04474).

### Notebooks
* [x] Low surface brightness source detection
* [ ] Low surface brightness measurement

### References
* [Greco LSB.ipynb](https://github.com/RobertLuptonTheGood/notebooks/blob/master/Demos/Greco%20LSB.ipynb)
* [Tune Detection.ipynb](https://github.com/RobertLuptonTheGood/notebooks/blob/master/Demos/Tune%20Detection.ipynb)
* [Kron.ipynb](https://github.com/RobertLuptonTheGood/notebooks/blob/master/Demos/Kron.ipynb).

**Comment by kadrlica** [comment]
I should look into `%matplotlib ipympl` for interactive plotting at NCSA.

**Comment by drphilmarshall** [comment]
The first part of Alex's project (LSB detection) is now merged, and can be viewed in the notebook at https://github.com/LSSTScienceCollaborations/StackClub/blob/master/SourceDetection/LowSurfaceBrightness.ipynb (with review at #55 ). Nice work, @kadrlica !

**Comment by drphilmarshall** [comment]
Oops - leaving this open, to track Part 2! :-)

**Comment by kadrlica** [comment]
From reading [Greco et al. 2017](https://arxiv.org/abs/1709.04474), it seems like low surface brightness measurement with the LSST stack may be more of a research project than a stack club tutorial. I think that a separate project could be measurement of higher-surface brightness sources.

I'm going to re-close this issue for the time being.
