### ISSUE TITLE
Session Plan for the LSST 2018 Project and Community Workshop

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#61]
Let's start making a plan for our Monday afternoon Stack Club session at the Tucson PCW (August 13). We'll have 90 mins, 1:30pm-3pm. I've pasted in below [the abstract on the PCW website](https://project.lsst.org/meetings/lsst2018/content/lsst-software-community-stack-club), now we need to flesh this out into a set of presentations and structured discussion. The goal is to kick off Phase 2 of the Stack Club (which will run through the fall) really well. @Madejski could you please make a start in a suitable named and permission-ed Google doc, and share it in this thread for us to iterate on? Thanks!

> ### LSST Software Community "Stack Club"
>
> Come and learn about the LSST processing software (the "LSST Software Stack") by working your way through one of our community-built tutorial Jupyter notebooks, and then extending it to do the things you are most interested in. We'll provide access to a JupyterLab instance, so no installation will be required: you can just jump in. We'll give you a quick guided tour of the tutorials we've got, and a demonstration of one of them in action. Then, we'll break up into a short hack session. The DM Stack Club is an LSSTC-supported initiative that will keep going by video through the Fall: you can get started in Tucson at the PCW, and then carry on learning with us when you get home.

**Comment by Madejski** [comment]
I made some additions to Phil's top-level overview of our Session at the Tucson meeting.  Not sure how to add permissions for the people who are part of this thread - or, should I just make it accessible for everyone?  --Greg

**Comment by kadrlica** [comment]
The planning document that Greg and Phil have been working on can be found [here](https://docs.google.com/document/d/1lxvOcqBSbvC6VZdeji16O2mcgGDHVgeF61y9E-86VvU).

**Comment by drphilmarshall** [comment]
Some ideas reposted from the August 10 meeting issue #85 : 

* Greg suggested we have the 3 notebook authors (@stargaser , @kadrlica , @bechtol ) connect to the BlueJeans room (muted!) during the session, so that they can share screen if needed during the discussion session in the second half. 

* Greg also suggested we explicitly point people to at least one of the Tuesday DM hack sessions, for people who want to spend more time thinking about the Stack Club and working on our notebooks. We'll need to look at the schedule to see which of these sessions we are available to attend.

The draft slides are [here](https://docs.google.com/presentation/d/1LWShGi-YLqWoxPvewkg-JOpb67WKZyI0YQcSFrmAl14/edit?usp=sharing), comments welcome (in place, please!). I'll also post them to our  [agenda page](https://project.lsst.org/meetings/lsst2018/content/lsst-software-community-stack-club) so that they are already there waiting for us when we arrive. (And so people can get a preview as well, if they want it.)

**Comment by drphilmarshall** [comment]
Video from Monday's PCW session is now up, on the [meetings page](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Meetings.md). Thanks to everyone who helped make it excellent - we had 51 people on the LSP!
