### ISSUE TITLE
Project: HSC Re-run 

### ISSUE THREAD

**Issue by jtmyles** [LSSTScienceCollaborations/StackClub#63]
I'm interested in cosmology with LSST lensed quasars, so would like to understand the whole DRP pipeline through to forced photometry light curves. I know this is a lot to learn, but with the html tutorials at pipelines.lsst.io I wonder whether I might be able to piece them together to do a complete re-run of a small patch of HSC sky? I'd want to pick a patch that contained a lens, to make it interesting. All advice gratefully received, and I'll start by reading through the html while identifying and displaying an HSC lens from Sonnenfeld et al 2018: http://adsabs.harvard.edu/abs/2018PASJ...70S..29S

This project has a lot of overlap with Andrew's in #58 - let's swap notes, @andrewkbradshaw!

**Comment by drphilmarshall** [comment]
Completed, and closed by #86 ! Well done, @jtmyles :-)
