### ISSUE TITLE
Basics: A Guided Tour of afw.display

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/StackClub#65]
I think that it would be very useful to have a notebook that went through the `afw.display` interface, with some documentation on the various backends. Some background on the philosophy of `afw.display` would likely be helpful for users.

**Comment by kadrlica** [comment]
@brantr sounds like you are interested in this project!

**Comment by kadrlica** [comment]
I'm also happy to help with this. Depending on what you want, we could imagine a "Novice" and "Expert" sections.

**Comment by brantr** [comment]
OK, I started a new branch to make a notebook to demo lsst.afw.display. Thanks for suggesting this.

**Comment by brantr** [comment]
With a working tutorial, I think we should consider this closed. Thanks to @kadrlica for the masked region addition.
