### ISSUE TITLE
Stack Club Rules - suggestions welcome!

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#75]
Thinking about Phase 2 of the Stack Club (beginning next Monday, with a bunch of new people at the PCW), let's write down some Rules for ourselves. Please suggest modifications and additional Rules in the comments below, and I'll keep this top comment up to date as we go. Agreeing to these rules would be a condition of joining the club and being granted an LSP account - so we'd put a set of checkboxes on our application form. Thanks!

### Stack Club Rules
As Stack Club members, we agree:

1.  **To each maintain the tutorial notebooks that we own.** The owners of each notebook will be written into its top cell, right under the notebook title. Notebooks that fail to run will be flagged as such; issues pointing out broken notebooks can be posted by anyone. 

2. **To code-review other club members' tutorial notebooks when requested.** After approval, a pull requests may be merged by the notebook owner or the Stack Club admins.	

3. **To write high quality tutorial notebooks** following the [contribution guidelines](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/GettingStarted.md#contributing-to-the-stack-club-repo). A [template notebook](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/templates/template_Notebook.ipynb) is provided to help with this.

4. **To attend and participate in Stack Club sessions** in order to create and maintain an active learning community. 

5. **To give way to others when necessary.** The Stack Club has only a limited number of LSP accounts: if we are not actively developing our Stack Club project, we won't mind if a new member takes our place while our own LSP account is de-activated (possibly temporarily).  

6. **To follow the LSST community guidelines** as laid out at https://community.lsst.org/faq when participating in club sessions and interacting with fellow members on Slack and GitHub, in order to foster an open, inclusive and respectful working environment.

**Comment by drphilmarshall** [comment]
Proposed new rule: 

> 4. **To write high quality tutorial notebooks** following the [contribution guidelines](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/GettingStarted.md#contributing-to-the-stack-club-repo). A [template notebook](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/templates/template_Notebook.ipynb) is provided to help with this.

**Comment by drphilmarshall** [comment]
Proposed new rules: 

> 5. **To attend at least 50% of the Stack Club sessions** in order to create and maintain an active learning community.

> 6. **To give way to others when necessary.** The Stack Club has only a limited number of LSP accounts: if we are not actively developing our Stack Club project, we won't mind if a new member takes our place while our own LSP account is de-activated (possibly temporarily).

**Comment by kadrlica** [comment]
How about:

5. *To attend and participate in Stack Club sessions* in order to create and maintain an active learning community.

**Comment by drphilmarshall** [comment]
With a tweak from Alex, I think the above list of rules is ready to post. I'll make a tiny md file in the Getting Started folder and close this out.

**Comment by drphilmarshall** [comment]
Closed by #84
