### ISSUE TITLE
Contribute image quality demo notebook

### ISSUE THREAD

**Issue by bechtol** [LSSTScienceCollaborations/StackClub#77]
Add a notebook with examples of how to measure the image quality and perform shape measurements with the Stack

**Comment by drphilmarshall** [comment]
@bechtol's completed image quality demo notebook is now merged: see #78 for the review and https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Validation/image_quality_demo.ipynb for the notebook. Thanks Keith!
