### ISSUE TITLE
stack version for beavis?

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/StackClub#83]
@drphilmarshall I noticed that a recent rendering of the low surface brightness notebook now detects the low surface brightness galaxy before the source removal and convolution (see image below). While this may be the result of a very minor configuration change in the stack, it breaks the story of the notebook. To avoid situations like this I think we should consider standardizing the version of the stack that's used to run beavis.

![image](https://user-images.githubusercontent.com/5605123/43865921-a031802c-9b29-11e8-89cc-32362174a295.png)

**Comment by drphilmarshall** [comment]
Agreed. I looked into this: at the moment I only know how to run `beavis-ci` (or even `jupyter nbconvert`) with one `--kernel` option, and that's `lsst`. The effect is to use the most recent release, v16.0. (You can now see that in cell no. 1 of the [rendered version of your notebook](https://nbviewer.jupyter.org/github/LSSTScienceCollaborations/StackClub/blob/rendered/SourceDetection/LowSurfaceBrightness.nbconvert.ipynb).)  So , I think we should standardize to the most recent release, at any given point in time. This was also Paul Price's recommendation, in the Slack discussion of this issue ( #74 ). I'll go address that now.
