### ISSUE TITLE
Phase 1 Stack Club Session, Friday August 10, 0900 PDT

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#85]
@LSSTScienceCollaborations/stack-club 

Looking forward to seeing you on Friday, August 10, 0900 PDT - our last session of Phase 1, before we kick off Phase 2 at the LSST 2018 PCW next week!

This week we'll take a quick look at some recent additions to our club repo:
* The [Stack Club Rules](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Rules.md)
* The [`stackclub` library package](https://github.com/LSSTScienceCollaborations/StackClub/tree/master/stackclub), for useful modules, classes, functions etc, including [docs](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/GettingStarted.md#the-stack-club-library)
* Improved ["Getting Started"](https://github.com/LSSTScienceCollaborations/StackClub/tree/master/GettingStarted) folder, including notebooks on:
  * [Finding Docs](https://nbviewer.jupyter.org/github/LSSTScienceCollaborations/StackClub/blob/rendered/GettingStarted/FindingDocs.nbconvert.ipynb)
  * [Import Tricks](https://nbviewer.jupyter.org/github/LSSTScienceCollaborations/StackClub/blob/rendered/GettingStarted/ImportTricks.nbconvert.ipynb)
* [Semi-continous integration and testing](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/CIT.md) of all notebooks in `master`, leading to badged folder README files like [this one](https://github.com/LSSTScienceCollaborations/StackClub/tree/master/GettingStarted)

And then, we'll briefly review [Monday's PCW Session plan](https://github.com/LSSTScienceCollaborations/StackClub/issues/61#issuecomment-411606684) in case we have last minute thoughts about it.

See you soon, on http://stanford.zoom.us/j/946390572 !

Phil

**Comment by drphilmarshall** [comment]
While looking at the `stackclub` package, Alex noted that `where_is` currently returns links to the `master` branch of the relevant repo, whereas really what we need is a pointer to the _v16.0 commit_ We think this ought to be possible, and @kadrlica said he would issue this fix. 

We also talked about the `wimport` and `nbimport` functions having the potential to either go stale or otherwise be hard to support - and so agreed that we may need to jettison them if that happens. We'll see...

**Comment by drphilmarshall** [comment]
A few good ideas about the Monday session: 

* Greg suggested we have the 3 notebook authors (David, Alex, Keith) connect to the BlueJeans room (muted!) during the session, so that they can share screen if needed during the discussion session in the second half. 

* Greg also suggested we explicitly point people to at least one of the Tuesday DM hack sessions, for people who want to spend more time thinking about the Stack Club and working on our notebooks. We'll need to look at the schedule to see which of these sessions we are available to attend.

The draft slides are [here](https://docs.google.com/presentation/d/1LWShGi-YLqWoxPvewkg-JOpb67WKZyI0YQcSFrmAl14/edit?usp=sharing), comments welcome (in place, please!). I'll add them to the [session plan issue](https://github.com/LSSTScienceCollaborations/StackClub/issues/61#issuecomment-411606684) as well, and also post them to the  agenda page.

**Comment by kadrlica** [comment]
@drphilmarshall I suggest that the first thing we do in the session is ask people to sign up for LSP accounts if they want to participate in the interactive second half of the agenda. We can give instructions and have them try to work through it while we talk.

**Comment by drphilmarshall** [comment]
Video for last week's meeting (Friday August 10) is now up on the meetings page](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Meetings.md).
