### ISSUE TITLE
Provide Twinkles truth catalog

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTScienceCollaborations/StackClub#99]
Since the twinkles data is available to the stack club it would be useful to provide a truth catalog for the sprinkled objects.

**Comment by jbkalmbach** [comment]
So, I have a set of the sprinkled AGN locations and the lens locations for use. Where should these go for sharing?

**Comment by drphilmarshall** [comment]
Thanks Bryce! I think they go in the /project/shared/data area, in the
twinkles subset folder. I think you can scp them in to the LSP once you are
there, and if I were you I'd add them in a folder called "truth" (which
hopefully the butler will not notice). Thanks!

**Comment by jbkalmbach** [comment]
Ok, the truth catalogs for Twinkles are now in `/project/shared/data/Twinkles_subset/truth`
